'use client'

import { useState, useEffect, useCallback } from 'react'
import { createClient } from '@/lib/supabase/client'
import { useRouter } from 'next/navigation'
import { Heart, ChatCircle } from '@phosphor-icons/react'
import Link from 'next/link'
import { cleanText } from '@/lib/profanity'

interface Props {
  post: any
  user: any
  liked: boolean
  isDetail?: boolean
}

function getRelativeTime(dateStr: string) {
  const now = new Date()
  const date = new Date(dateStr)
  const diffMs = now.getTime() - date.getTime()
  const diffMin = Math.floor(diffMs / 60000)
  const diffHours = Math.floor(diffMs / 3600000)
  const diffDays = Math.floor(diffMs / 86400000)
  const diffWeeks = Math.floor(diffDays / 7)

  if (diffMin < 1) return 'just now'
  if (diffMin < 60) return `${diffMin}m`
  if (diffHours < 24) return `${diffHours}h`
  if (diffDays < 7) return `${diffDays}d`
  if (diffDays < 30) return `${diffWeeks}w`

  return `${date.getMonth() + 1}/${date.getDate()}/${date.getFullYear()}`
}

function isAutoGenerated(body: string) {
  return /^@\S+ conquered .+$/i.test(body.trim())
}

const FEED_COMMENT_LIMIT = 3

export default function PostCard({ post, user, liked, isDetail = false }: Props) {
  const [isLiked, setIsLiked] = useState(liked)
  const [likeCount, setLikeCount] = useState(post.post_likes[0]?.count ?? 0)
  const [showComments, setShowComments] = useState(isDetail)
  const [comments, setComments] = useState<any[]>([])
  const [commentBody, setCommentBody] = useState('')
  const [loadingComment, setLoadingComment] = useState(false)
  const [loadingLike, setLoadingLike] = useState(false)
  const router = useRouter()

  const loadComments = useCallback(async () => {
    const supabase = createClient()
    const { data } = await supabase
      .from('post_comments')
      .select('*, profiles(full_name, username)')
      .eq('post_id', post.id)
      .order('created_at', { ascending: true })
    setComments(data ?? [])
  }, [post.id])

  useEffect(() => {
    if (isDetail) {
      loadComments()
    }
  }, [isDetail, loadComments])

  const handleLike = async () => {
    if (!user || loadingLike) return
    setLoadingLike(true)
    const supabase = createClient()

    if (isLiked) {
      await supabase.from('post_likes').delete().eq('post_id', post.id).eq('user_id', user.id)
      setIsLiked(false)
      setLikeCount((c: number) => c - 1)
    } else {
      await supabase.from('post_likes').insert({ post_id: post.id, user_id: user.id })
      setIsLiked(true)
      setLikeCount((c: number) => c + 1)

      if (post.user_id !== user.id) {
        const { error: notifError } = await supabase.from('notifications').insert({
          user_id: post.user_id,
          actor_id: user.id,
          type: 'like',
          reference_id: post.id,
          message: 'liked your post',
        })
        if (notifError) {
          console.error('like notification failed:', notifError.message, notifError.code)
        }
      }
    }
    setLoadingLike(false)
  }

  const handleToggleComments = async () => {
    if (!showComments) await loadComments()
    setShowComments(!showComments)
  }

  const handleComment = async (e: React.FormEvent) => {
    e.preventDefault()
    if (!commentBody.trim() || !user) return
    setLoadingComment(true)
    const supabase = createClient()
    const cleanedBody = await cleanText(commentBody)

    await supabase.from('post_comments').insert({
      post_id: post.id,
      user_id: user.id,
      body: cleanedBody,
    })

    if (post.user_id !== user.id) {
      const { error: notifError } = await supabase.from('notifications').insert({
        user_id: post.user_id,
        actor_id: user.id,
        type: 'comment',
        reference_id: post.id,
        message: 'commented on your post',
      })
      if (notifError) {
        console.error('comment notification failed:', notifError.message, notifError.code)
      }
    }

    setCommentBody('')
    await loadComments()
    setLoadingComment(false)
    router.refresh()
  }

  const mountainName = post.mountains?.name?.replace(/^Mount\s+/i, 'Mt. ')
  const elevation = post.mountains?.elevation

  const showBody = post.is_conquest
    ? post.body && post.body.trim() && !isAutoGenerated(post.body)
    : !!post.body

  const totalCommentCount = post.post_comments[0]?.count ?? 0
  const visibleComments = isDetail ? comments : comments.slice(0, FEED_COMMENT_LIMIT)
  const hiddenCount = comments.length > FEED_COMMENT_LIMIT ? comments.length - FEED_COMMENT_LIMIT : 0

  return (
    <div style={{ paddingTop: '14px', paddingBottom: '14px', borderBottom: '1px solid #f3f4f6' }}>

      {/* Author row */}
      <div style={{ display: 'flex', alignItems: 'center', gap: '8px', marginBottom: '8px' }}>
        {post.profiles?.avatar_url && (
          <img
            src={post.profiles.avatar_url}
            alt=""
            style={{ width: '28px', height: '28px', borderRadius: '50%', objectFit: 'cover', flexShrink: 0 }}
          />
        )}
        <div style={{ display: 'flex', alignItems: 'center', gap: '5px', flexWrap: 'wrap' }}>
          <Link
            href={`/profile/${post.profiles?.username}`}
            style={{ fontSize: '13px', fontWeight: 600, textDecoration: 'none', color: 'inherit' }}
          >
            @{post.profiles?.username ?? post.profiles?.full_name ?? 'Anonymous'}
          </Link>
          <span style={{ color: '#d1d5db', fontSize: '12px' }}>·</span>
          <span style={{ fontSize: '12px', color: '#9ca3af' }}>
            {getRelativeTime(post.created_at)}
          </span>
          {post.is_conquest && mountainName && (
            <>
              <span style={{ color: '#d1d5db', fontSize: '12px' }}>·</span>
              <Link
                href={`/mountains/${post.mountain_id}`}
                style={{ fontSize: '12px', color: '#9ca3af', textDecoration: 'none' }}
              >
                {`Conquered `}{mountainName}{elevation && ` · ${elevation} masl`}
              </Link>
            </>
          )}
        </div>
      </div>

      {showBody && (
        <p style={{ fontSize: '13px', color: '#374151', lineHeight: 1.6, marginBottom: '8px' }}>
          {post.body}
        </p>
      )}

      {post.image_url && (
        <div style={{ marginBottom: '10px', borderRadius: '10px', overflow: 'hidden', backgroundColor: '#f3f4f6' }}>
          {isDetail ? (
            <img
              src={post.image_url}
              alt="Post image"
              style={{ width: '100%', height: 'auto', display: 'block' }}
            />
          ) : (
            <Link href={`/posts/${post.id}?from=feed`} style={{ display: 'block' }}>
              <img
                src={post.image_url}
                alt="Post image"
                style={{ width: '100%', height: 'auto', display: 'block' }}
              />
            </Link>
          )}
        </div>
      )}

      {!post.is_conquest && post.mountains && (
        <div style={{ marginBottom: '10px' }}>
          <span style={{ fontSize: '11px', backgroundColor: '#f3f4f6', color: '#6b7280', padding: '3px 8px', borderRadius: '6px', fontWeight: 500 }}>
            {mountainName} · {elevation} masl
          </span>
        </div>
      )}

      {/* Actions */}
      <div style={{ display: 'flex', gap: '16px' }}>
        <button
          onClick={handleLike}
          disabled={!user || loadingLike}
          style={{
            display: 'flex', alignItems: 'center', gap: '5px',
            fontSize: '13px', background: 'none', border: 'none', cursor: 'pointer', padding: 0,
            color: isLiked ? '#ef4444' : '#9ca3af',
            opacity: (!user || loadingLike) ? 0.4 : 1,
          }}
        >
          <Heart size={15} weight={isLiked ? 'fill' : 'regular'} />
          <span>{likeCount}</span>
        </button>

        <button
          onClick={handleToggleComments}
          style={{
            display: 'flex', alignItems: 'center', gap: '5px',
            fontSize: '13px', background: 'none', border: 'none', cursor: 'pointer', padding: 0,
            color: '#9ca3af',
          }}
        >
          <ChatCircle size={15} weight={showComments ? 'fill' : 'regular'} />
          <span>{totalCommentCount}</span>
        </button>
      </div>

      {/* Comments */}
      {showComments && (
        <div style={{ marginTop: '12px', borderTop: '1px solid #f3f4f6', paddingTop: '12px' }}>
          {comments.length > 0 ? (
            <div style={{ display: 'grid', gap: '10px', marginBottom: '12px' }}>
              {visibleComments.map((comment) => (
                <div key={comment.id}>
                  <p style={{ fontSize: '12px', fontWeight: 600, color: '#6b7280' }}>
                    @{comment.profiles?.username ?? comment.profiles?.full_name ?? 'Anonymous'}
                  </p>
                  <p style={{ fontSize: '13px', color: '#374151', marginTop: '2px' }}>{comment.body}</p>
                </div>
              ))}

              {!isDetail && hiddenCount > 0 && (
                <Link
                  href={`/posts/${post.id}?from=feed`}
                  style={{ fontSize: '13px', color: '#6b7280', textDecoration: 'none', fontWeight: 500 }}
                >
                  View {hiddenCount} more comment{hiddenCount > 1 ? 's' : ''}
                </Link>
              )}
            </div>
          ) : (
            <p style={{ fontSize: '13px', color: '#9ca3af', marginBottom: '12px' }}>No comments yet.</p>
          )}

          {user && (
            <form onSubmit={handleComment} style={{ display: 'flex', gap: '8px' }}>
              <input
                type="text"
                value={commentBody}
                onChange={(e) => setCommentBody(e.target.value)}
                placeholder="Write a comment..."
                style={{ flex: 1, border: '1px solid #e5e7eb', borderRadius: '10px', padding: '7px 12px', fontSize: '13px', backgroundColor: '#f9fafb', fontFamily: 'inherit', outline: 'none' }}
              />
              <button
                type="submit"
                disabled={loadingComment || !commentBody.trim()}
                style={{ backgroundColor: '#111827', color: '#ffffff', padding: '7px 14px', borderRadius: '10px', fontSize: '13px', border: 'none', cursor: 'pointer', opacity: loadingComment || !commentBody.trim() ? 0.5 : 1, fontFamily: 'inherit' }}
              >
                {loadingComment ? '...' : 'Send'}
              </button>
            </form>
          )}
        </div>
      )}
    </div>
  )
}